package model.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAskCash<M extends BaseAskCash<M>> extends Model<M> implements IBean {

	public void setAskCashId(java.lang.Integer askCashId) {
		set("askCashId", askCashId);
	}

	public java.lang.Integer getAskCashId() {
		return get("askCashId");
	}

	public void setCashUserId(java.lang.Integer cashUserId) {
		set("cashUserId", cashUserId);
	}

	public java.lang.Integer getCashUserId() {
		return get("cashUserId");
	}

	public void setCashIntegral(java.lang.Double cashIntegral) {
		set("cashIntegral", cashIntegral);
	}

	public java.lang.Double getCashIntegral() {
		return get("cashIntegral");
	}

	public void setCashState(java.lang.Integer cashState) {
		set("cashState", cashState);
	}

	public java.lang.Integer getCashState() {
		return get("cashState");
	}

	public void setCashTime(java.util.Date cashTime) {
		set("cashTime", cashTime);
	}

	public java.util.Date getCashTime() {
		return get("cashTime");
	}

}
