package model.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAnimalIncome<M extends BaseAnimalIncome<M>> extends Model<M> implements IBean {

	public void setIncomeId(java.lang.Integer incomeId) {
		set("incomeId", incomeId);
	}

	public java.lang.Integer getIncomeId() {
		return get("incomeId");
	}

	public void setIncomeAnimalId(java.lang.Integer incomeAnimalId) {
		set("incomeAnimalId", incomeAnimalId);
	}

	public java.lang.Integer getIncomeAnimalId() {
		return get("incomeAnimalId");
	}

	public void setAnimalIncomeNum(java.lang.Integer animalIncomeNum) {
		set("animalIncomeNum", animalIncomeNum);
	}

	public java.lang.Integer getAnimalIncomeNum() {
		return get("animalIncomeNum");
	}

	public void setAnimalIncomeCount(java.lang.Integer animalIncomeCount) {
		set("animalIncomeCount", animalIncomeCount);
	}

	public java.lang.Integer getAnimalIncomeCount() {
		return get("animalIncomeCount");
	}

	public void setAnimalIncomeTime(java.util.Date animalIncomeTime) {
		set("animalIncomeTime", animalIncomeTime);
	}

	public java.util.Date getAnimalIncomeTime() {
		return get("animalIncomeTime");
	}

}
