package model.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCashMessage<M extends BaseCashMessage<M>> extends Model<M> implements IBean {

	public void setCashMessageId(java.lang.Integer cashMessageId) {
		set("cashMessageId", cashMessageId);
	}

	public java.lang.Integer getCashMessageId() {
		return get("cashMessageId");
	}

	public void setCashMessageContent(java.lang.String cashMessageContent) {
		set("cashMessageContent", cashMessageContent);
	}

	public java.lang.String getCashMessageContent() {
		return get("cashMessageContent");
	}

	public void setCashMessageState(java.lang.Integer cashMessageState) {
		set("cashMessageState", cashMessageState);
	}

	public java.lang.Integer getCashMessageState() {
		return get("cashMessageState");
	}

}
