package model.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseAnimal<M extends BaseAnimal<M>> extends Model<M> implements IBean {

	public void setAnimalId(java.lang.Integer animalId) {
		set("animalId", animalId);
	}

	public java.lang.Integer getAnimalId() {
		return get("animalId");
	}

	public void setAniFarmId(java.lang.Integer aniFarmId) {
		set("aniFarmId", aniFarmId);
	}

	public java.lang.Integer getAniFarmId() {
		return get("aniFarmId");
	}

	public void setIncomeCount(java.lang.Integer incomeCount) {
		set("incomeCount", incomeCount);
	}

	public java.lang.Integer getIncomeCount() {
		return get("incomeCount");
	}

	public void setCurrCount(java.lang.Integer currCount) {
		set("currCount", currCount);
	}

	public java.lang.Integer getCurrCount() {
		return get("currCount");
	}

	public void setIsFeed(java.lang.Integer isFeed) {
		set("isFeed", isFeed);
	}

	public java.lang.Integer getIsFeed() {
		return get("isFeed");
	}

	public void setFeedTime(java.util.Date feedTime) {
		set("feedTime", feedTime);
	}

	public java.util.Date getFeedTime() {
		return get("feedTime");
	}

}
