package model.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLandTree<M extends BaseLandTree<M>> extends Model<M> implements IBean {

	public void setLandTreeId(java.lang.Integer landTreeId) {
		set("landTreeId", landTreeId);
	}

	public java.lang.Integer getLandTreeId() {
		return get("landTreeId");
	}

	public void setLandId(java.lang.Integer landId) {
		set("landId", landId);
	}

	public java.lang.Integer getLandId() {
		return get("landId");
	}

	public void setTreeFarmId(java.lang.Integer treeFarmId) {
		set("treeFarmId", treeFarmId);
	}

	public java.lang.Integer getTreeFarmId() {
		return get("treeFarmId");
	}

	public void setTreeType(java.lang.Integer treeType) {
		set("treeType", treeType);
	}

	public java.lang.Integer getTreeType() {
		return get("treeType");
	}

	public void setFruitsNum(java.lang.Integer fruitsNum) {
		set("fruitsNum", fruitsNum);
	}

	public java.lang.Integer getFruitsNum() {
		return get("fruitsNum");
	}

	public void setCurrFruitNum(java.lang.Integer currFruitNum) {
		set("currFruitNum", currFruitNum);
	}

	public java.lang.Integer getCurrFruitNum() {
		return get("currFruitNum");
	}

	public void setIsRich(java.lang.Integer isRich) {
		set("isRich", isRich);
	}

	public java.lang.Integer getIsRich() {
		return get("isRich");
	}

	public void setGetRichTime(java.util.Date getRichTime) {
		set("getRichTime", getRichTime);
	}

	public java.util.Date getGetRichTime() {
		return get("getRichTime");
	}

}
