package model.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUser<M extends BaseUser<M>> extends Model<M> implements IBean {

	public void setUserId(java.lang.Integer userId) {
		set("userId", userId);
	}

	public java.lang.Integer getUserId() {
		return get("userId");
	}

	public void setRealName(java.lang.String realName) {
		set("realName", realName);
	}

	public java.lang.String getRealName() {
		return get("realName");
	}

	public void setUserPhone(java.lang.String userPhone) {
		set("userPhone", userPhone);
	}

	public java.lang.String getUserPhone() {
		return get("userPhone");
	}

	public void setPassWord(java.lang.String passWord) {
		set("passWord", passWord);
	}

	public java.lang.String getPassWord() {
		return get("passWord");
	}

	public void setWeixinId(java.lang.String weixinId) {
		set("weixinId", weixinId);
	}

	public java.lang.String getWeixinId() {
		return get("weixinId");
	}

	public void setBankId(java.lang.String bankId) {
		set("bankId", bankId);
	}

	public java.lang.String getBankId() {
		return get("bankId");
	}

	public void setRefereeId(java.lang.Integer refereeId) {
		set("refereeId", refereeId);
	}

	public java.lang.Integer getRefereeId() {
		return get("refereeId");
	}

	public void setAddTime(java.util.Date addTime) {
		set("addTime", addTime);
	}

	public java.util.Date getAddTime() {
		return get("addTime");
	}

	public void setUserRole(java.lang.Long userRole) {
		set("userRole", userRole);
	}

	public java.lang.Long getUserRole() {
		return get("userRole");
	}

	public void setUserMoney(java.lang.Double userMoney) {
		set("userMoney", userMoney);
	}

	public java.lang.Double getUserMoney() {
		return get("userMoney");
	}

	public void setFarmIntegral(java.lang.Double farmIntegral) {
		set("farmIntegral", farmIntegral);
	}

	public java.lang.Double getFarmIntegral() {
		return get("farmIntegral");
	}

	public void setFertilizer(java.lang.Long fertilizer) {
		set("fertilizer", fertilizer);
	}

	public java.lang.Long getFertilizer() {
		return get("fertilizer");
	}

	public void setRemainMeat(java.lang.Integer remainMeat) {
		set("remainMeat", remainMeat);
	}

	public java.lang.Integer getRemainMeat() {
		return get("remainMeat");
	}

	public void setFarmType(java.lang.Integer farmType) {
		set("farmType", farmType);
	}

	public java.lang.Integer getFarmType() {
		return get("farmType");
	}

	public void setFarmAnimal(java.lang.Integer farmAnimal) {
		set("farmAnimal", farmAnimal);
	}

	public java.lang.Integer getFarmAnimal() {
		return get("farmAnimal");
	}

	public void setAnimalDueTime(java.lang.Long animalDueTime) {
		set("animalDueTime", animalDueTime);
	}

	public java.lang.Long getAnimalDueTime() {
		return get("animalDueTime");
	}

}
