package model.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseOpenLand<M extends BaseOpenLand<M>> extends Model<M> implements IBean {

	public void setOpenLandId(java.lang.Integer openLandId) {
		set("openLandId", openLandId);
	}

	public java.lang.Integer getOpenLandId() {
		return get("openLandId");
	}

	public void setFarmId(java.lang.Integer farmId) {
		set("farmId", farmId);
	}

	public java.lang.Integer getFarmId() {
		return get("farmId");
	}

	public void setLandId(java.lang.Integer landId) {
		set("landId", landId);
	}

	public java.lang.Integer getLandId() {
		return get("landId");
	}

	public void setOpenLandTime(java.util.Date openLandTime) {
		set("openLandTime", openLandTime);
	}

	public java.util.Date getOpenLandTime() {
		return get("openLandTime");
	}

}
