package model.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseLand<M extends BaseLand<M>> extends Model<M> implements IBean {

	public void setLandId(java.lang.Integer landId) {
		set("landId", landId);
	}

	public java.lang.Integer getLandId() {
		return get("landId");
	}

	public void setIsOpen(java.lang.Integer isOpen) {
		set("isOpen", isOpen);
	}

	public java.lang.Integer getIsOpen() {
		return get("isOpen");
	}

	public void setFarmId(java.lang.Integer farmId) {
		set("farmId", farmId);
	}

	public java.lang.Integer getFarmId() {
		return get("farmId");
	}

	public void setLandType(java.lang.Integer landType) {
		set("landType", landType);
	}

	public java.lang.Integer getLandType() {
		return get("landType");
	}

}
