package model.basemodel;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSteal<M extends BaseSteal<M>> extends Model<M> implements IBean {

	public void setStealId(java.lang.Integer stealId) {
		set("stealId", stealId);
	}

	public java.lang.Integer getStealId() {
		return get("stealId");
	}

	public void setFarmId(java.lang.Integer farmId) {
		set("farmId", farmId);
	}

	public java.lang.Integer getFarmId() {
		return get("farmId");
	}

	public void setStrealTreeId(java.lang.Integer strealTreeId) {
		set("strealTreeId", strealTreeId);
	}

	public java.lang.Integer getStrealTreeId() {
		return get("strealTreeId");
	}

	public void setStealFruitNum(java.lang.Integer stealFruitNum) {
		set("stealFruitNum", stealFruitNum);
	}

	public java.lang.Integer getStealFruitNum() {
		return get("stealFruitNum");
	}

	public void setStealTime(java.util.Date stealTime) {
		set("stealTime", stealTime);
	}

	public java.util.Date getStealTime() {
		return get("stealTime");
	}

}
