package model.dao;


import java.util.List;

import model.basemodel.BaseAnimal;

import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Animal extends BaseAnimal<Animal> {
	public static final Animal dao = new Animal();

	/**
	 * 用户购买神兽 
	 * @author wh
	 * @since 2016-11-14
	 * @param farmId
	 */
	public void buyAnimal(Object farmId) {
		this.set("animalId", null);
		this.set("aniFarmId", farmId);
		this.save();
	}

	/**
	 * 查询该农场的神兽
	 * @author wh
	 * @since 2016-11-14
	 * @param farmId
	 * @return 
	 */
	public Animal findAnimalByFarmId(Object farmId) {
		String sql = "SELECT * FROM t_animal WHERE aniFarmId = ?";
		return this.findFirst(sql, farmId);
	}

	/**
	 * 查询该农场的神兽收益详情
	 * @author wh
	 * @since 2016-11-15
	 * @param farmId
	 * @return
	 */
	public Record findAnimalIncomeDetail(String farmId) {
		String sql = "SELECT * FROM t_animal AS ta LEFT JOIN (SELECT MAX(animalIncomeTime) AS animalIncomeTime,incomeAnimalId";
		sql += " FROM t_animal_income GROUP BY incomeAnimalId) AS tai ON tai.incomeAnimalId = ta.animalId WHERE ta.aniFarmId = ?";
		sql += " AND ta.isFeed = 1";
		return Db.findFirst(sql, farmId);
	}

	/**
	 * 获得该神兽今天的收益
	 * @author wh
	 * @since 2016-11-15
	 * @param animalId
	 * @return
	 */
	public String findIncomeCount(Object animalId) {
		String sql = "SELECT SUM(animalIncomeNum) AS animalIncomeNum FROM t_animal_income WHERE incomeAnimalId = ? AND animalIncomeTime >= CURRENT_DATE()";
		Record record = Db.findFirst(sql, animalId);
		return String.valueOf(record.get("animalIncomeNum"));
	}

	/**
	 * 清除神兽的喂食状态
	 * @author wh
	 * @since 2016-11-15
	 */
	public void clearFeed() {
		String sql = "SELECT * FROM t_animal";
		List<Animal> animals = this.find(sql);
		for(Animal animal : animals){
			animal.set("isFeed", 0);
			animal.set("currCount", 0);
			animal.set("feedTime", null);
			animal.update();
		}
	}

	/**
	 * 删除收益到达120的神兽
	 * @author wh
	 * @since 2016-11-15
	 */
	public void deleteAnimal() {
		String sql = "SELECT * FROM t_animal WHERE incomeCount >= 120";
		String sql2 = "SELECT * FROM t_animal_income WHERE incomeAnimalId  = ?";
		List<Animal> animals = this.find(sql);
		for(Animal animal : animals){
			System.out.println("删除" + animal.get("animalId") + "号果树成功!");
			// 删除该神兽的收益记录
			for(AnimalIncome animalIncome : AnimalIncome.dao.find(sql2, animal.get("animalId"))){
				animalIncome.delete();
			}
			animal.delete();
		}
	}
}
