package model.dao;

import com.jfinal.plugin.activerecord.Page;

import model.basemodel.BaseAnimalIncome;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AnimalIncome extends BaseAnimalIncome<AnimalIncome> {
	public static final AnimalIncome dao = new AnimalIncome();

	public Page getDataList(Integer pageNumber, Integer pageSize, String sql) {
		return paginate(pageNumber, pageSize, sql);
	}
}
