package model.dao;

import java.util.List;

import com.jfinal.plugin.activerecord.Page;

import model.basemodel.BaseAskCash;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class AskCash extends BaseAskCash<AskCash> {
	public static final AskCash dao = new AskCash();

	@SuppressWarnings("rawtypes")
	public Page getDataList(Integer pageNumber, Integer pageSize, String sql) {
		return paginate(pageNumber, pageSize, sql);
	}

	/**
	 * 用户查询自己的提现记录
	 * @author wh
	 * @since 2016-11-12
	 * @param object
	 * @return 
	 */
	public List<AskCash> findAskCashRecord(Object userId) {
		String sql = "SELECT * FROM t_ask_cash WHERE cashUserId = ?";
		return this.find(sql, userId);
	}
}
