package model.dao;

import model.basemodel.BaseCashMessage;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class CashMessage extends BaseCashMessage<CashMessage> {
	public static final CashMessage dao = new CashMessage();
}
