package model.dao;

import model.basemodel.BaseOpenLand;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class OpenLand extends BaseOpenLand<OpenLand> {
	public static final OpenLand dao = new OpenLand();

	/**
	 * 判断该用户今天是否有开耕记录
	 * @author wh
	 * @since 2016-11-14
	 * @param farmId
	 */
	public boolean dayOpen(Object farmId) {
		String sql = "SELECT * FROM t_open_land WHERE openLandTime > CURRENT_DATE() AND farmId = ?";
		OpenLand openLand = this.findFirst(sql, farmId);
		if(openLand != null){// 今天已经开耕过
			return true;
		}else{
			return false;
		}
	}
}
