package model.dao;

import model.basemodel.BaseSteal;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Steal extends BaseSteal<Steal> {
	public static final Steal dao = new Steal();

	/**
	 * 查询该用户是否被偷取过果实 
	 * @author wh
	 * @since 2016-11-14
	 * @param steal
	 * @return 
	 */
	public Steal findSteal(String steal) {
		String sql  = "SELECT * FROM t_steal WHERE farmId = ? AND stealTime > CURRENT_DATE()";
		return this.findFirst(sql, steal);
	}
}
